### ISSUE TITLE
Dataframe does not load in same format as given in answer key

### ISSUE THREAD

**Issue by AnnikaNoren** [learn-co-curriculum/dsc-managing-time-series-data-lab#2]
Hi,
In the second cell of the lab, the code is provided to load the data frame.  My data comes out in the format with a "b" in front of the date: 

b'19580329' | 316.1

Even when I did a copy of the answer key, the same problem happened.

**Comment by hoffm386** [comment]
Hi @AnnikaNoren, thanks for submitting this! It looks like the issue was either with your local setup, or with StatsModels. Running this lab with the current version of `learn-env` (Python, pandas, and StatsModels) does not produce this behavior, so I'm going to go ahead and close out this issue.
